spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/playwithme
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        # show_sql: true


  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

