# 개발
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/playwithme?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '0114'

oauth2:
  kakao:
    login:
      redirect-uri: "http://localhost:8080/member/login/oauth/kakao/callback"
    logout:
      redirect-uri: "http://localhost:8080/member/logout/oauth/kakao"

