#Database
spring:
  profiles:
    include:
      - secret  # 중요 정보가 담긴 yml
    active: dev # 기본 개발 모드 활성화

  datasource:
    url: jdbc:mariadb://localhost:3306/playwithme?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '0114'

    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor: trace