spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pwm
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # show_sql: true


  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
