spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/pwm
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/play_with_me?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    driverClassName: org.mariadb.jdbc.Driver
    password: '0114'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # show_sql: true


  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
