name: Spring Boot & Gradle & Docker & EC2 CI/CD

# 실행 이벤트
on:
  push:
    branches:
      - develop
permissions:
  contents: read

# Job
jobs:
  build:
    runs-on: ubuntu-latest #ubuntu-22.04 로 실행
    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK version 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # application-secret.yml 파일 생성
      - name: Make ./src/main/resources/application-secret.yml
        run: |
          cd ./src/main/resources
          touch ./application-secret.yml
          echo "${{ secrets.APPLICATION_SECRET_YML }}" >> ./application-secret.yml
        shell: bash

      # Gradle build
      - name: Make gradlew executable
        run: chmod 744 ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      # Docker Image build, push
      - name: Build Docker Image For Spring Boot
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/playwithme .
          docker push ${{ secrets.DOCKER_USERNAME }}/playwithme

      # EC2 서버에서 Docker Container 실행
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker rm -f $(docker ps -qa)
            docker rmi ${{ secrets.DOCKER_USERNAME }}/playwithme
            docker pull ${{ secrets.DOCKER_USERNAME }}/playwithme
            docker-compose up -d
